# docker-compose.demo-c.yml
version: "3.9"

services:
  db:
    image: postgres:15
    container_name: demo_c_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER:  app
      POSTGRES_PASSWORD:  secret
      POSTGRES_DB:  app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: demo_c_pgadmin
    depends_on: [db]
    environment:
      PGADMIN_DEFAULT_EMAIL:  admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin_data: